args:
  path: "models/MC_OFA"
  checkpoint: "models/MC_OFA/model_best.pth.tar"
  model: "constant_V3"
  dataset: "imagenette"
  ks_list: [3, 5, 7]
  expand_list: [1, 2, 3, 4]
  depth_list: [2, 3, 4]
  dynamic_batch_size: 1
  base_lr: 3.0e-3
  manual_seed: 0
  lr_schedule_type: "cosine"
  base_batch_size: 64
  valid_size: 100
  opt_type: "sgd"
  momentum: 0.9
  no_nesterov: false
  weight_decay: 3.0e-5
  label_smoothing: 0.1
  no_decay_keys: "bn#bias"
  fp16_allreduce: false
  model_init: "he_fout"
  validation_frequency: 5
  print_frequency: 10
  n_worker: 12
  resize_scale: 0.08
  distort_color: "tf"
  image_size: [128, 160, 192, 224]
  continuous_size: true
  not_sync_distributed_image_size: false
  bn_momentum: 0.1
  bn_eps: 1.0e-5
  dropout: 0
  base_stage_width: "proxyless"
  width_mult_list: 1.0
  dy_conv_scaling_mode: 1
  independent_distributed_sampling: false
  kd_ratio: 1.0
  kd_type: "ce"

subnet_config:
  ks: [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]
  e: [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]
  d: [4, 4, 4, 4]
  image_size: 224
  res_dir: "res"
  name: "test"
  draw_graphs: true
