TEST: false

args:
  path: "models/supernet/constant_imagenet_low_lr"
  teacher_path: "models/teacher/constant_inet_200_epochs"
  pretrained_model_path: "models/teacher/constant_inet_200_epochs"
  model: "constant_V3"
  dataset: "imagenet"
  res_dir: "res"
  ks_list: [3, 5, 7]
  expand_list: [1, 2, 3, 4]
  depth_list: [2, 3, 4]
  dynamic_batch_size: 1
  base_lr: 3.0e-3
  manual_seed: 0
  lr_schedule_type: "cosine"
  base_batch_size: 64
  valid_size: 100
  opt_type: "sgd"
  momentum: 0.9
  no_nesterov: false
  weight_decay: 3.0e-5
  label_smoothing: 0.1
  no_decay_keys: "bn#bias"
  fp16_allreduce: false
  model_init: "he_fout"
  validation_frequency: 1
  print_frequency: 10
  n_worker: 12
  resize_scale: 0.08
  distort_color: "tf"
  image_size: [128, 160, 192, 224]
  continuous_size: true
  not_sync_distributed_image_size: false
  bn_momentum: 0.1
  bn_eps: 1.0e-5
  dropout: 0.1
  base_stage_width: "proxyless"
  width_mult_list: 1.0
  dy_conv_scaling_mode: 1
  independent_distributed_sampling: false
  kd_ratio: 1.0
  kd_type: "ce"

args_per_task:
  kernel_1:
    n_epochs: 120
    base_lr: 3.0e-3
    warmup_epochs: 5
    warmup_lr: 3.0e-3
    task_ks_list: [3, 5, 7]
    task_expand_list: [4]
    task_depth_list: [4]
    dynamic_batch_size: 1
  depth_1:
    n_epochs: 25
    base_lr: 2.5e-4
    warmup_epochs: 0
    warmup_lr: 2.5e-3
    task_ks_list: [3, 5, 7]
    task_expand_list: [4]
    task_depth_list: [3, 4]
    dynamic_batch_size: 2
  depth_2:
    n_epochs: 120
    base_lr: 7.5e-4
    warmup_epochs: 5
    warmup_lr: 7.5e-5
    task_ks_list: [3, 5, 7]
    task_expand_list: [4]
    task_depth_list: [2, 3, 4]
    dynamic_batch_size: 2
  expand_1:
    n_epochs: 25
    base_lr: 2.5e-4
    warmup_epochs: 0
    warmup_lr: 2.5e-5
    task_ks_list: [3, 5, 7]
    task_expand_list: [3, 4]
    task_depth_list: [2, 3, 4]
    dynamic_batch_size: 4
  expand_2:
    n_epochs: 25
    base_lr: 2.5e-4
    warmup_epochs: 0
    warmup_lr: 7.5e-4
    task_ks_list: [3, 5, 7]
    task_expand_list: [2, 3, 4]
    task_depth_list: [2, 3, 4]
    dynamic_batch_size: 4
  expand_3:
    n_epochs: 120
    base_lr: 7.5e-4
    warmup_epochs: 5
    warmup_lr: 7.5e-5
    task_ks_list: [3, 5, 7]
    task_expand_list: [1, 2, 3, 4]
    task_depth_list: [2, 3, 4]
    dynamic_batch_size: 4

tasks: ["kernel", "depth", "expand"]
tasks_phases:
  kernel: [1]
  depth: [1, 2]
  expand: [1, 2, 3]

# For eval only :
subnet_config:
  ks: [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]
  e: [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]
  d: [4, 4, 4, 4]
  image_size: 224
  name: "test"

wandb:
  use_wandb: true
  project_name: "once-for-all-memory-constant"
