name: moofa_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aom=3.5.0
  - appdirs=1.4.4
  - archspec=0.2.3
  - atk-1.0=2.38.0
  - binutils=2.39
  - binutils_impl_linux-64=2.39
  - binutils_linux-64=2.39
  - blas=2.116
  - blas-devel=3.9.0
  - boltons=24.0.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - c-compiler=1.7.0
  - ca-certificates=2024.8.30
  - cairo=1.18.0
  - ccache=4.10.1
  - certifi=2024.7.4
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cmake=3.29.4
  - colorama=0.4.6
  - conda=24.7.1
  - conda-libmamba-solver=24.7.0
  - conda-package-handling=2.3.0
  - conda-package-streaming=0.10.0
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.5.39
  - cuda-runtime=12.1.0
  - cuda-version=12.5
  - cudnn=8.9.7.29
  - cxx-compiler=1.7.0
  - distro=1.9.0
  - docker-pycreds=0.4.0
  - expat=2.6.2
  - ffmpeg=5.1.2
  - filelock=3.15.4
  - fmt=10.2.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozendict=2.4.4
  - gcc=12.2.0
  - gcc_impl_linux-64=12.2.0
  - gcc_linux-64=12.2.0
  - gdk-pixbuf=2.42.10
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gitdb=4.0.11
  - gitpython=3.1.43
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.7.9
  - graphite2=1.3.13
  - graphviz=9.0.0
  - gtk2=2.24.33
  - gts=0.7.6
  - gxx=12.2.0
  - gxx_impl_linux-64=12.2.0
  - gxx_linux-64=12.2.0
  - h2=4.1.0
  - harfbuzz=8.5.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.7
  - jinja2=3.1.4
  - jpeg=9e
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.39
  - lerc=4.0.0
  - libabseil=20240116.2
  - libarchive=3.7.4
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.10.0.4
  - libcurand=10.3.6.39
  - libcurl=8.8.0
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libdrm=2.4.122
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc=14.1.0
  - libgcc-devel_linux-64=12.2.0
  - libgcc-ng=14.1.0
  - libgd=2.3.3
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.80.2
  - libgomp=14.1.0
  - libhiredis=1.0.2
  - libhwloc=2.10.0
  - libiconv=1.17
  - libidn2=2.3.7
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnghttp2=1.58.0
  - libnl=3.9.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - librsvg=2.58.0
  - libsanitizer=12.2.0
  - libsolv=0.7.29
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx=14.1.0
  - libstdcxx-devel_linux-64=12.2.0
  - libstdcxx-ng=14.1.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libuv=1.48.0
  - libva=2.18.0
  - libvpx=1.11.0
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.5.8
  - markupsafe=2.1.5
  - menuinst=2.1.2
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpi=1.0
  - mpi4py=3.1.6
  - mpmath=1.3.0
  - nccl=2.22.3.1
  - ncurses=6.5
  - nettle=3.9.1
  - networkx=3.3
  - numpy=2.0.0
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openmpi=5.0.3
  - openssl=3.3.1
  - p11-kit=0.24.1
  - packaging=24.1
  - pango=1.54.0
  - pathtools=0.1.2
  - pcre2=10.43
  - pillow=10.4.0
  - pip=24.0
  - pixman=0.43.2
  - platformdirs=4.2.2
  - pluggy=1.5.0
  - protobuf=4.25.3
  - psutil=6.0.0
  - pthread-stubs=0.4
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.22
  - pydot=1.2.4
  - pysocks=1.7.1
  - python=3.11.9
  - python_abi=3.11
  - pytorch=2.3.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - readline=8.2
  - reproc=14.2.4.post0
  - reproc-cpp=14.2.4.post0
  - requests=2.32.3
  - rhash=1.4.4
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - sentry-sdk=2.7.1
  - setproctitle=1.3.3
  - setuptools=70.1.1
  - six=1.16.0
  - smmap=5.0.0
  - svt-av1=1.4.1
  - sympy=1.12.1
  - sysroot_linux-64=2.12
  - tbb=2021.12.0
  - tk=8.6.13
  - torchaudio=2.3.1
  - torchtriton=2.3.1
  - torchvision=0.18.1
  - tqdm=4.66.4
  - truststore=0.9.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - urllib3=2.2.2
  - wheel=0.43.0
  - x264=1!164.3095
  - x265=3.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zlib=1.2.13
  - zstandard=0.22.0
  - zstd=1.5.6
  - pip:
      - beautifulsoup4==4.12.3
      - cloudpickle==3.0.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - fonttools==4.53.1
      - gdown==5.2.0
      - git+https://github.com/thomas-bouvier/horovod.git@compile-cpp17
      - kiwisolver==1.4.5
      - matplotlib==3.9.1
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - graphviz==0.20.3
      - soupsieve==2.6
      - wandb==0.17.3
