TEST: false

args:
  path: "ablation_study/models/supernet/config2/"
  t_path: "ablation_study/models/teacher/config2/"  
  teacher_path: "ablation_study/models/teacher/config2/"
  pretrained_model_path: "ablation_study/models/teacher/config2"
  checkpoint: "ablation_study/models/supernet/config2/checkpoint/checkpoint-expand_2.pth.tar"
  model: "constant_V2"
  dataset: "imagenette"
  res_dir: "res"
  ks_list: [3, 5, 7]
  expand_list: [1, 1.5, 2]
  depth_list: [2, 3, 4]
  n_epochs: 180
  warmup_epochs: 0
  warmup_lr: 3.0e-3 
  dynamic_batch_size: 1
  base_lr: 3.0e-3
  manual_seed: 0
  lr_schedule_type: "cosine"
  base_batch_size: 128 
  valid_size: 100
  opt_type: "sgd"
  momentum: 0.9
  no_nesterov: false
  weight_decay: 3.0e-5
  label_smoothing: 0.1
  no_decay_keys: "bn#bias"
  fp16_allreduce: false
  model_init: "he_fout"
  validation_frequency: 1
  print_frequency: 10
  n_worker: 12
  resize_scale: 0.08
  distort_color: "tf"
  image_size: [128, 160, 192, 224]
  continuous_size: true
  not_sync_distributed_image_size: false
  bn_momentum: 0.1
  bn_eps: 1.0e-5
  dropout: 0.1
  base_stage_width: "proxyless"
  width_mult_list: 1.0
  dy_conv_scaling_mode: 1
  independent_distributed_sampling: false
  kd_ratio: 1.0
  kd_type: "ce"

args_per_task:
  kernel_1:
    n_epochs: 120
    base_lr: 3.0e-3
    warmup_epochs: 5
    warmup_lr: 3.0e-3
    task_ks_list: [3, 5, 7]
    task_expand_list: [2]
    task_depth_list: [4]
    dynamic_batch_size: 1
  depth_1:
    n_epochs: 25
    base_lr: 2.5e-4
    warmup_epochs: 0
    warmup_lr: 2.5e-3
    task_ks_list: [3, 5, 7]
    task_expand_list: [2]
    task_depth_list: [3, 4]
    dynamic_batch_size: 2
  depth_2:
    n_epochs: 120
    base_lr: 7.5e-4
    warmup_epochs: 5
    warmup_lr: 7.5e-5
    task_ks_list: [3, 5, 7]
    task_expand_list: [2]
    task_depth_list: [2, 3, 4]
    dynamic_batch_size: 2
  expand_1:
    n_epochs: 25
    base_lr: 2.5e-4
    warmup_epochs: 0
    warmup_lr: 2.5e-5
    task_ks_list: [3, 5, 7]
    task_expand_list: [1.5, 2]
    task_depth_list: [2, 3, 4]
    dynamic_batch_size: 4
  expand_2:
    n_epochs: 120
    base_lr: 2.5e-4
    warmup_epochs: 5
    warmup_lr: 7.5e-5
    task_ks_list: [3, 5, 7]
    task_expand_list: [1, 1.5, 2]
    task_depth_list: [2, 3, 4]
    dynamic_batch_size: 4

tasks: ["kernel", "depth", "expand"]
tasks_phases:
  kernel: [1]
  depth: [1, 2]
  expand: [1, 2]

# For eval only :
subnet_config:
  ks: [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]
  e: [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]
  d: [4, 4, 4, 4]
  image_size: 224
  name: "test"

search_config:
  N_constraint: 20
  max_constraint: 800000
  min_constraint: 300000
  res_dir: "ablation_study/searches/config2/"
  acc_dataset_path: "ablation_study/acc_predictor_datasets/config2/dataset.pkl"
  acc_predictor_checkpoint: "ablation_study/acc_predictor_checkpoints/config2.pth.tar"

wandb:
  use_wandb: true
  project_name: "once-for-all-memory-constant"
